/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Medicamento;
import javax.swing.JOptionPane;

/**
 *
 * @author Breno Mendes Bernardo
 */
public class Main extends javax.swing.JFrame {
    
    private Medicamento m;

    public Main() {
        initComponents();
        this.m = new Medicamento();
    }
    
    private boolean IsFloat(String Valor) {
        try {
            float f = Float.parseFloat(Valor);
            return true;
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
            return false;
            
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidade = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        txtaltura = new javax.swing.JTextField();
        cbgenero = new javax.swing.JComboBox<>();
        lblidade = new javax.swing.JLabel();
        lblpeso = new javax.swing.JLabel();
        lblaltura = new javax.swing.JLabel();
        lblgenero = new javax.swing.JLabel();
        txtgotas = new javax.swing.JTextField();
        txtpercgordura = new javax.swing.JTextField();
        txtsitcorp = new javax.swing.JTextField();
        txtpesoideal = new javax.swing.JTextField();
        lblgotas = new javax.swing.JLabel();
        lblpercgordura = new javax.swing.JLabel();
        lblsitcorp = new javax.swing.JLabel();
        lblpesoideal = new javax.swing.JLabel();
        btncalcular = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidadeActionPerformed(evt);
            }
        });

        txtaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalturaActionPerformed(evt);
            }
        });

        cbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        cbgenero.setSelectedIndex(-1);
        cbgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgeneroActionPerformed(evt);
            }
        });

        lblidade.setText("Idade");

        lblpeso.setText("Peso");

        lblaltura.setText("Altura");

        lblgenero.setText("Gênero");

        txtgotas.setEditable(false);
        txtgotas.setBackground(new java.awt.Color(204, 204, 204));
        txtgotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgotasActionPerformed(evt);
            }
        });

        txtpercgordura.setEditable(false);
        txtpercgordura.setBackground(new java.awt.Color(204, 204, 204));

        txtsitcorp.setEditable(false);
        txtsitcorp.setBackground(new java.awt.Color(204, 204, 204));

        txtpesoideal.setEditable(false);
        txtpesoideal.setBackground(new java.awt.Color(204, 204, 204));

        lblgotas.setText("Total gotas");

        lblpercgordura.setText("Percentual de Gordura");

        lblsitcorp.setText("Situação Corpórea");

        lblpesoideal.setText("Peso Ideal");

        btncalcular.setBackground(new java.awt.Color(0, 153, 0));
        btncalcular.setForeground(new java.awt.Color(0, 0, 0));
        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        btnlimpar.setBackground(new java.awt.Color(255, 0, 0));
        btnlimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblsitcorp, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
                            .addComponent(txtsitcorp)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblgotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
                            .addComponent(txtgotas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblaltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(86, 86, 86))
                            .addComponent(txtaltura)
                            .addComponent(txtidade))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblpeso, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addGap(13, 13, 13))
                                    .addComponent(lblgenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbgenero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtpeso, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblpercgordura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblpesoideal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(65, 65, 65))
                                    .addComponent(txtpesoideal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpercgordura, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnlimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jSeparator2)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblpeso, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpeso, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidade)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblaltura, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtaltura, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblgenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbgenero)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblgotas, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgotas, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblsitcorp, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsitcorp, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtpercgordura))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblpercgordura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28)))
                        .addGap(18, 18, 18)
                        .addComponent(lblpesoideal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesoideal)))
                .addGap(28, 28, 28)
                .addComponent(btncalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidadeActionPerformed

    private void txtalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalturaActionPerformed

    private void cbgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgeneroActionPerformed

    private void txtgotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgotasActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        if (txtidade.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
            txtidade.requestFocus(); 
        }
        else if (cbgenero.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
            cbgenero.requestFocus();        
        }
        else if (IsFloat(txtpeso.getText())&&
                IsFloat(txtaltura.getText())){
            
            this.m.setIdade(Integer.parseInt(txtidade.getText()));
            this.m.setPeso(Float.parseFloat(txtpeso.getText()));
            this.m.setAltura(Float.parseFloat(txtaltura.getText()));
            this.m.setGenero(cbgenero.getSelectedIndex());
            
            txtgotas.setText(String.format("%d", this.m.getGotas()));
            txtpercgordura.setText(String.format("%.2f", this.m.getPG()) + "%");
            txtsitcorp.setText(this.m.getSitCorporea());
            txtpesoideal.setText(String.format("%.2f", this.m.getPesoideal()) + " kg");
        }
        

    }//GEN-LAST:event_btncalcularActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        // TODO add your handling code here:
        txtidade.setText("");
        txtaltura.setText("");
        txtpeso.setText("");
        txtgotas.setText("");
        txtpercgordura.setText("");
        txtpesoideal.setText("");
        txtsitcorp.setText("");
        cbgenero.setSelectedIndex(-1);
        txtidade.requestFocus();
    }//GEN-LAST:event_btnlimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JComboBox<String> cbgenero;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblaltura;
    private javax.swing.JLabel lblgenero;
    private javax.swing.JLabel lblgotas;
    private javax.swing.JLabel lblidade;
    private javax.swing.JLabel lblpercgordura;
    private javax.swing.JLabel lblpeso;
    private javax.swing.JLabel lblpesoideal;
    private javax.swing.JLabel lblsitcorp;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtgotas;
    private javax.swing.JTextField txtidade;
    private javax.swing.JTextField txtpercgordura;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtpesoideal;
    private javax.swing.JTextField txtsitcorp;
    // End of variables declaration//GEN-END:variables
}
